spring.application.name=bank-management-system

# Server port for Railway
server.port=${PORT:8080}

# database configurations for connecting to mysql database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa and hibernate properties/configurations

#this will show the sql queries running internally in console
spring.jpa.show-sql=true
#for automatically update database after every change
spring.jpa.hibernate.ddl-auto=update
#it converts the java data types into database data type
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false